# -*- coding: utf-8 -*-
"""
@author: Joel Leckie

Created on Sun Apr. 09, 2023
"""


class Blocks:
    box_hor_light = hor_thin = hor_wall = u'\u2500'
    box_hor_heavy = hor_thick = hor_fort = u'\u2501'
    box_ver_light = ver_thin = ver_wall = u'\u2502'
    box_ver_heavy = ver_thick = ver_fort = u'\u2503'
    double_dash_hor_light = hor_2dash_thin = window_hor = u'\u254C'
    double_dash_hor_heavy = hor_2dash_thick = window_heavy_hor = u'\u254D'
    double_dash_ver_light = ver_2dash_thin = window_ver = u'\u254E'
    double_dash_ver_heavy = ver_2dash_thick = window_heavy_ver = u'\u254F'
    triple_dash_hor_light = hor_3dash_thin = door_hor = u'\u2504'
    triple_dash_hor_heavy = hor_3dash_thick = door_heavy_hor = u'\u2505'
    triple_dash_ver_light = ver_3dash_thin = door_ver = u'\u2506'
    triple_dash_ver_heavy = ver_3dash_thick = door_heavy_ver = u'\u2507'
    quad_dash_hor_light = hor_4dash_thin = gate_hor = u'\u2508'
    quad_dash_hor_heavy = hor_4dash_thick = gate_heavy_hor = u'\u2509'
    quad_dash_ver_light = ver_4dash_thin = gate_ver = u'\u250A'
    quad_dash_ver_heavy = ver_4dash_thick = gate_heavy_ver = u'\u250B'
    down_right_light = nw_thin = nw_wall = u'\u250C'
    down_right_heavy = nw_thick = nw_fort = u'\u250F'
    down_left_light = ne_thin = ne_wall = u'\u2510'
    down_left_heavy = ne_thick = ne_fort = u'\u2513'
    up_right_light = sw_thin = sw_wall = u'\u2514'
    up_right_heavy = sw_thick = sw_fort = u'\u2517'
    up_left_light = se_thin = se_wall = u'\u2518'
    up_left_heavy = se_thick = se_fort = u'\u251B'
    ver_right_light = west_t_thin = west_t_wall = u'\u251C'
    ver_right_heavy = west_t_thick = west_t_fort = u'\u2523'
    ver_left_light = east_t_thin = east_t_wall = u'\u2524'
    ver_left_heavy = east_t_thick = east_t_fort = u'\u252B'
    hor_down_light = north_t_thin = north_t_wall = u'\u252C'
    hor_down_heavy = north_t_thick = north_t_fort = u'\u2533'
    hor_up_light = south_t_thin = south_t_wall = u'\u2534'
    hor_up_heavy = south_t_thick = south_t_fort = u'\u253B'
    ver_hor_light = cross_thin = center_plus_wall = u'\u253C'
    ver_hor_heavy = cross_thick = center_plus_fort = u'\u254B'
    box_double_hor = hor_double = hor_castle = u'\u2550'
    box_double_ver = ver_double = ver_castle = u'\u2551'
    double_down_right = nw_double = nw_castle = u'\u2554'
    double_down_left = ne_double = ne_castle = u'\u2557'
    double_up_right = sw_double = sw_castle = u'\u255A'
    double_up_left = se_double = se_castle = u'\u255D'
    double_ver_right = west_t_double = west_t_castle = u'\u2560'
    double_ver_left = east_t_double = east_t_castle = u'\u2563'
    double_hor_down = north_t_double = north_t_castle = u'\u2566'
    double_hor_up = south_t_double = south_t_castle = u'\u2569'
    double_ver_hor = cross_double = center_plus_castle = u'\u256C'
    diagonal_cross = u'\u2573'

    nw_curve = u'\u256D'
    ne_curve = u'\u256E'
    se_curve = u'\u256F'
    sw_curve = u'\u2570'
    nw_quadrant = u'\25DC'
    ne_quadrant = u'\25DD'
    se_quadrant = u'\25DE'
    sw_quadrant = u'\25DF'

    space = u'\u0020'
    thin_block = u'\u2591'
    med_block = u'\u2592'
    thick_block = u'\u2593'
    solid_block = u'\u2588'
    angle_box = pillar = u'\u25C8'
    flower = u'\u2698'

    player_m = u'u+1FBC5'
    player_f = u'u+1FBC9'
    npc = mob = u'u+1FBC6'
    tree = u'\u2359'
    bush = u'u+1FBB0'


